### ISSUE TITLE
Crate does not support all IANA-registered COSE header parameters

### ISSUE THREAD

**Issue by henrylyons** [tramires/cose-rust#1]
While experimenting with this crate, I got the following error when decoding a COSE message with a x5chain header value: InvalidLabel(33). 

After reviewing headers.rs, I verified that this crate only supports a subset of the IANA-registered COSE header parameters (https://www.iana.org/assignments/cose/cose.xhtml). For example, none of the x5* header parameters (x5bag, x5chain, x5u, x5t) are supported.

Are there any plans to implement support for these headers?

**Comment by tramires** [comment]
Yes, but only after the final development of the features specified in the COSE RFC (https://tools.ietf.org/html/rfc8152). Unfortunately, for now, I can't give an estimate of when the rest will be implemented.

**Comment by henrylyons** [comment]
Thanks for the update. Are you open to having others contribute to this project? I am interested in having a complete implementation of CoseSign1.
