### ISSUE TITLE
External Contributions

### ISSUE THREAD

**Issue by henrylyons** [tramires/cose-rust#2]
I am looking for a full CoseSign1 implementation in Rust, that supports all the signing algorithms and headers listed in the IANA COSE registry. Are you open to getting external contributions to complete your CoseSign1 implementation? If so, can I contact you offline (email, Zoom call, etc.) to discuss this further?

**Comment by tramires** [comment]
Not at the moment since this project is related to my thesis, but as I have the same interest in the CoseSign1 specifically, I will start developing the missing CoseSign algorithms (EdDSA with Ed448 and RSA-PSS) and headers (x5*, x5*-sender) soon.

**Comment by tramires** [comment]
Ed448, RSA-PSS and x5* added in new update.
